const songs = [
    {
        ID: "NEVQ",
        NAME: "Ngày Em Vu Quy",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGAYEMVUQUY-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/2ix1ns96v8qc26fyizvm7/NGAYEMVUQUY-XUANKEN.mp3?rlkey=hw5ro0z9pgg4qua16ys6ofrtk&st=st9ckyf3&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGAYEMVUQUY-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/vd8p2aztg2oqgwvan49nh/NGAYEMVUQUY-LYRIC.lrc?rlkey=e80y122dz8ge8y60tz0e12fry&st=plt9z1sw&dl=0",
    },
    {
        ID: "TTLBAN",
        NAME: "Thất Tình & Làm Bạn Anh Nhé",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/THATTINHLAMBANANHNHE-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/g4k5j0x9j0bbfvt3eta9t/THATTINHLAMBANANHNHE-XUANKEN.mp3?rlkey=h1s2unsb9n0ii3poub0eu43u6&st=dbwmvk8z&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/THATTINHLAMBANANHNHE-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/6bm5qyx5t5a7fq6n68p3r/THATTINHLAMBANANHNHE-LYRIC.lrc?rlkey=3hop1nkywgwso083mdwltv7z2&st=o8nh6zok&dl=0",
    },
    {
        ID: "QNDN",
        NAME: "Quên Nhau Đi Nhé",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/QUENNHAUDINHE-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/y7oitkaozlf1tk1bp2lh1/QUENNHAUDINHE-XUANKEN.mp3?rlkey=y3pb2acbc5db4rgnkzdmu3bb3&st=8c1hu39q&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/QUENNHAUDINHE-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/58jy9lgo054nhgybeowpu/QUENNHAUDINHE-LYRIC.lrc?rlkey=sdsf40n4a0nddbhqpctgb2ob0&st=8ckarrkq&dl=0",
    },
    {
        ID: "AME",
        NAME: "Ánh Mắt Em",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/ANHMATEM-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/bjxmvn0nk43h81w1y6r8a/ANHMATEM-XUANKEN.mp3?rlkey=4tzanju49d63qkc27cdziu51g&st=mvrnng6s&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/ANHMATEM-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/re28enq6huuyhkibdyxq6/ANHMATEM-LYRIC.lrc?rlkey=5t87c99zogg7q5a3ugss02n0u&st=fnfjr5zq&dl=0",
    },
    {
        ID: "DEBNK",
        NAME: "Để Em Bên Người Khác",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DEEMBENNGUOIKHAC-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/bco0g3mdeiwrjsmyqsyv6/DEEMBENNGUOIKHAC-XUANKEN.mp3?rlkey=9gto06vls3tcnc92mn050qex2&st=042c9xjv&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DEEMBENNGUOIKHAC-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/sdw6mh5s2jbo4fmv5sjqr/DEEMBENNGUOIKHAC-LYRIC.lrc?rlkey=9ztqriimvtc3dp2x9kh536ayu&st=j0wuhpoh&dl=0",
    },
    {
        ID: "NOLTT",
        NAME: "Người Ở Lại Trong Tim",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIOLAITRONGTIM-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/glwck81hgjka16k9q183l/NGUOIOLAITRONGTIM-XUANKEN.mp3?rlkey=i3p7j7tr4dkpzfpo1oyz0z79h&st=mrzm37ux&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIOLAITRONGTIM-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/nk7f9jnzixbckjxur6wiw/NGUOIOLAITRONGTIM-LYRIC.lrc?rlkey=ftjbip4j30voaiyptthhkq4hn&st=uz38oyzp&dl=0",
    },
    {
        ID: "DEMR",
        NAME: "Dính Em Mất Rồi",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DINHEMMATROI-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/cfqtazmwwi5uetvuz8sgk/DINHEMMATROI-XUANKEN.mp3?rlkey=k48q2oh8gof6da5gkqnp55n1v&st=6jssy0zf&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DINHEMMATROI-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/l34neac0q9979eba51trr/DINHEMMATROI-LYRIC.lrc?rlkey=c14ci8ghv3ukslx30ngso68be&st=8xrbs75m&dl=0",
    },
    {
        ID: "SCMLNN",
        NAME: "Sau Cơn Mưa Là Nỗi Nhớ",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAUCONMUALANOINHO-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/ybt4ie8n1rkvodpzanz37/SAUCONMUALANOINHO-XUANKEN.mp3?rlkey=hqqplne8gn0pz5mpbo464m9sw&st=57lmttit&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAUCONMUALANOINHO-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/qh2y72mmiazu8zg81490p/SAUCONMUALANOINHO-LYRIC.lrc?rlkey=z1mtyfuta0jv2j16fypkfh8za&st=3ulsx4em&dl=0",
    },
    {
        ID: "NOLGM",
        NAME: "Người Ở Lại Giữa Mưa",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIOLAIGIUAMUA-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/g4x7mxd3q00pntnxgwzp9/NGUOIOLAIGIUAMUA-XUANKEN.mp3?rlkey=s1pe96tibyiwp1eq8krv12t0z&st=g22qdfog&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIOLAIGIUAMUA-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/qjseeej3866khpdn5jh3q/NGUOIOLAIGIUAMUA-LYRIC.lrc?rlkey=mqsly2tfhzk3ejlorry7gbxb2&st=u4ajumn2&dl=0",
    },
    {
        ID: "GHNLCD",
        NAME: "Giữa Hai Người Là Cô Đơn",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/GIUAHAINGUOILACODON-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/uv8e3378ffc2vpc4vimc4/GIUAHAINGUOILACODON-XUANKEN.mp3?rlkey=crnbvb9vktzozmt0940ubhusw&st=817tfrhc&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/GIUAHAINGUOILACODON-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/50zvqzbm7qjcc80q4ajv3/GIUAHAINGUOILACODON-LYRIC.lrc?rlkey=rif6162gbidnq1z60kojcl515&st=ch0uu30y&dl=0",
    },
    {
        ID: "CTDLOD",
        NAME: "Chúng Ta Dừng Lại Ở Đây",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHUNGTADUNGLAIODAY-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/xf7ctz25m23af8fmpcjdc/CHUNGTADUNGLAIODAY-XUANKEN.mp3?rlkey=62mr2hadwouba3vyts6us548e&st=k7efytfj&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHUNGTADUNGLAIODAY-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/zt6uwa21nj4a7rf2yl5yk/CHUNGTADUNGLAIODAY-LYRIC.lrc?rlkey=1tdkw5gllx62rddklruznn0xf&st=2tkdiozi&dl=0",
    },
    {
        ID: "DCVLA",
        NAME: "Đến Cuối Vẫn Là Anh",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DENCUOIVANLAANH-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/k1df0ha02l6cu7zj71ez0/DENCUOIVANLAANH-XUANKEN.mp3?rlkey=51o310ybx6oooatdw4fyc2y1e&st=kanurgew&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DENCUOIVANLANH-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/owe5ld6aghuml5gejonxh/DENCUOIVANLANH-LYRIC.lrc?rlkey=gghijpfo7ijmvnzki5j33celt&st=iwwwc0fe&dl=0",
    },
    {
        ID: "VQNVT",
        NAME: "Về Quảng Ninh Với Tôi",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/VEQUANGNINHVOITOI-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/f306jvn3vl4p5cwygptdu/VEQUANGNINHVOITOI-XUANKEN.mp3?rlkey=36e07p5u5olykp6u3ygdzwtbf&st=fqgorzn7&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/VEQUANGNINHVOITOI-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/yjeve4nfqbvpos32vnztd/VEQUANGNINHVOITOI-LYRIC.lrc?rlkey=mwck80s4qzbjoukcmlsdblzsj&st=108lsdsf&dl=0",
    },
    {
        ID: "AYESTD",
        NAME: "Anh Yêu Em Sai Thời Điểm",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/ANHYEUEMSAITHOIDIEM-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/4i6cgievzz4iv63p9maze/ANHYEUEMSAITHOIDIEM-XUANKEN.mp3?rlkey=2akpj5xnjg9q2gi2pqosabm81&st=lkr9n1i5&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/ANHYEUEMSAITHOIDIEM-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/s5517uy35ox6el8z10im9/ANHYEUEMSAITHOIDIEM-LYRIC.lrc?rlkey=w63rlr78wr0ai9iwuonsxoovq&st=a3kkuixr&dl=0",
    },
    {
        ID: "DCTHP",
        NAME: "Đợi Chờ Trong Hạnh Phúc",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DOICHOTRONGHANHPHUC-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/i6knkkziozjb96llznl5x/DOICHOTRONGHANHPHUC-XUANKEN.mp3?rlkey=jn2bc2nou1kq9p61gpddtw9cx&st=w8o50bm3&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DOICHOTRONGHANHPHUC-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/ic1tvdnvo72f0oglk4s0l/DOICHOTRONGHANHPHUC-LYRIC.lrc?rlkey=cs5c4hru19ngxpzeoxn8b1w2j&st=o0bct67o&dl=0",
    },
    {
        ID: "ECLBT",
        NAME: "Em Chỉ Là Bạn Thân",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/EMCHILABANTHAN-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/g4wy0ph5xbw1xe6jiloxs/EMCHILABANTHAN-XUANKEN.mp3?rlkey=1nvjs671dua8vs5998j0l5u9e&st=hmcwhswl&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/EMCHILABANTHAN-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/3b7g06t00gbnfb2lyldkx/EMCHILABANTHAN-LYRIC.lrc?rlkey=r1z5dw8n21j5dton39kbe0dkj&st=fobw0zmd&dl=0",
    },
    {
        ID: "KHI",
        NAME: "Khi",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/KHI-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/zhpyu4foriy96avkvtx5t/KHI-XUANKEN.mp3?rlkey=3a3tqb62axoqwnszc340j3c11&st=pmyh4n6c&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/KHI-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/3sia20fm98mzwpy5oomrq/KHI-LYRIC.lrc?rlkey=j0uit3g16nfjatkt8vdsdzsd8&st=kagj33fn&dl=0",
    },
    {
        ID: "CTLBV1",
        NAME: "Chuyến Tàu Ly Biệt (Ver 1)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHUYENTAULYBIETV1-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/itwl4qmf52swpx16zpuiw/CHUYENTAULYBIETV1-XUANKEN.mp3?rlkey=uug7me80pghelshev8alzy1mr&st=yhg50rjx&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHUYENTAULYBIETV1-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/8aql77b6gu8vhgg5mlc3o/CHUYENTAULYBIETV1-LYRIC.lrc?rlkey=a7w0qp5n7qzztu8nevhwkptnn&st=56mijmwo&dl=0",
    },
    {
        ID: "CTLBV2",
        NAME: "Chuyến Tàu Ly Biệt (Ver 2)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHUYENTAULYBIETV2-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/6si135ztin6lcxiaxjthn/CHUYENTAULYBIETV2-XUANKEN.mp3?rlkey=g0hnxr8pbemyv782edmeuvxhb&st=rzq1ianv&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHUYENTAULYBIETV2-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/94g0rzxtzw3g49dxrfpws/CHUYENTAULYBIETV2-LYRIC.lrc?rlkey=xvxa50qb8yt9hc0j1tp74dui1&st=ub7p1t5u&dl=0",
    },
    {
        ID: "50NVS",
        NAME: "50 Năm Về Sau",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/50NAMVESAU-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/gx7lmver0no1ds2fg7xq3/50NAMVESAU-XUANKEN.mp3?rlkey=o3hrdj1nfkmts6nyll9gr6m8e&st=c3juscsq&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/50NAMVESAU-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/shskp35a337ofgyc3lzss/50NAMVESAU-LYRIC.lrc?rlkey=esgzd3ou6z3w8n5xk8c8k7min&st=2eqqh9ha&dl=0",
    },
    {
        ID: "PCCENA",
        NAME: "Phố Cũ Còn Em (Ver Nam)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/PHOCUCONEM-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/hdhgb71qdnb8umpikx2zc/PHOCUCONEM-XUANKEN.mp3?rlkey=4antz9cak1qomr5a388ufpnwg&st=1p432yqb&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/PHOCUCONEM-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/tsmlyaonhe1tpupc03vfk/PHOCUCONEM-LYRIC.lrc?rlkey=ll8sfbadhxt6wgezf54redbw9&st=dg2ghga9&dl=0",
    },
    {
        ID: "PCCANU",
        NAME: "Phố Cũ Còn Anh (Ver Nữ)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/PHOCUCONANH-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/ecd36mpc0fwln8uayf1ob/PHOCUCONANH-XUANKEN.mp3?rlkey=a6cgjphx3k835fj0bsez7q0n0&st=thwtxs8o&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/PHOCUCONANH-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/r7hz6azahisadc6fkmkji/PHOCUCONANH-LYRIC.lrc?rlkey=7tffm91ckfczqll8vb9ty27hd&st=rpvcyswq&dl=0",
    },
    {
        ID: "NKOL",
        NAME: "Người Không Ở Lại",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIKHONGOLAI-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/8abmzuqfakf6fbdkg24hf/NGUOIKHONGOLAI-XUANKEN.mp3?rlkey=070shp3aupj7c279ohptidcqj&st=oox5m476&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIKHONGOLAI-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/tn7hynsb1hi2galaid4cq/NGUOIKHONGOLAI-LYRIC.lrc?rlkey=za2vc3txmkxlqjqw16dkdp9hv&st=gyzupiuo&dl=0",
    },
    {
        ID: "MLVA",
        NAME: "Mở Lòng Vì Ai",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/MOLONGVIAI-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/2zd1wjb03tb3k3ba0z3ds/MOLONGVIAI-XUANKEN.mp3?rlkey=6fauh5zswmdgf1zojg8ktoo4w&st=ap5i0b5z&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/MOLONGVIAI-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/3lct6f7oov7nwcfwbb540/MOLONGVIAI-LYRIC.lrc?rlkey=2zzhdyuahqvpiv93lfcsd64vr&st=8rgkp4ve&dl=0",
    },
    {
        ID: "ATAT",
        NAME: "Anh Thua Anh Ta",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/ANHTHUAANHTA-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/ks07aijjdbrhig5emukf2/ANHTHUAANHTA-XUANKEN.mp3?rlkey=e99e54mwuq8371pot2bqtonuv&st=oeebbrr1&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/ANHTHUAANHTA-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/j7wcy41ledd6mcxy9c574/ANHTHUAANHTA-LYRIC.lrc?rlkey=4jygdn9cm34pe2ifad6bw5npf&st=ca8dns4f&dl=0",
    },
    {
        ID: "CCNNNU",
        NAME: "Có Chút Ngọt Ngào (Ver Nữ)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/COCHUTNGOTNGAONU-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/jj0rfg3hgn29kan17yw3d/COCHUTNGOTNGAONU-XUANKEN.mp3?rlkey=sl25xj6o977i4ec9r12hfsfon&st=8j4svwjf&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/COCHUTNGOTNGAONU-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/nu9fvjej9alp5jer9uvqg/COCHUTNGOTNGAONAM-LYRIC.lrc?rlkey=gqkp0rkh4h4bdxxx5ls4v71vy&st=2nk8cgxt&dl=0",
    },
    {
        ID: "CCNNNA",
        NAME: "Có Chút Ngọt Ngào (Ver Nam)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/COCHUTNGOTNGAONAM-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/ia8dyq8rsc98fikfce0zr/COCHUTNGOTNGAONAM-XUANKEN.mp3?rlkey=6zknjbdoglz86pga5k2zy45wz&st=e2hjfkdg&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/COCHUTNGOTNGAONAM-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/nu9fvjej9alp5jer9uvqg/COCHUTNGOTNGAONAM-LYRIC.lrc?rlkey=gqkp0rkh4h4bdxxx5ls4v71vy&st=2nk8cgxt&dl=0",
    },
    {
        ID: "BTTTNU",
        NAME: "Bên Tách Trà Thơm (Ver Nữ)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/BENTACHTRATHOMNU-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/xmvov370ukauo6onn1gf2/BENTACHTRATHOMNU-XUANKEN.mp3?rlkey=zfuts0yscqqvts6v7s7g0xqv8&st=9ojbt0lw&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/BENTACHTRATHOMNU-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/ulqccle4hse176qc747pj/BENTACHTRATHOMNU-LYRIC.lrc?rlkey=yanwbm67t0pxur4hgosw6klvp&st=xm8t9vcv&dl=0",
    },
    {
        ID: "BTTTNA",
        NAME: "Bên Tách Trà Thơm (Ver Nam)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/BENTACHTRATHOMNAM-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/am7ldgzplcftj3y27lnod/BENTACHTRATHOMNAM-XUANKEN.mp3?rlkey=et4mpw2qixg2ve7dzsw4k3dlt&st=y2g4vw76&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/BENTACHTRATHOMNAM-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/8w2l5akni8rvqtn1vlljk/BENTACHTRATHOMNAM-LYRIC.lrc?rlkey=yt8a0sdi0uo7ywhjrmel48euz&st=wzntz7xo&dl=0",
    },
    {
        ID: "CON",
        NAME: "Cảm Ơn Nhé",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CAMONNHE-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/8nippzv9z1tpz8cyg3ut0/CAMONNHE-XUANKEN.mp3?rlkey=p2mbpeguwmyoeyqmvh0nqey9g&st=bav6msre&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CAMONNHE-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/xp3i60cp7drktyh3eogw0/CAMONNHE-LYRIC.lrc?rlkey=xskite6tijtlqqydpi5bsd1v9&st=m04xm21l&dl=0",
    },
    {
        ID: "SLH",
        NAME: "Sau Lời Hứa",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAULOIHUA-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/qiduzyfsjh7vvgvhgpdo4/SAULOIHUA-XUANKEN.mp3?rlkey=gov4w3tm22y5xdnin806niyc7&st=vy0hfcl1&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAULOIHUA-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/tiunqs1qhabr74w3bz4th/SAULOIHUA-LYRIC.lrc?rlkey=ynkwurnc3kltl30g442fwfcmb&st=ozlkxqj5&dl=0",
    },
    {
        ID: "TK",
        NAME: "Tình Khuyết",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TINHKHUYET-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/4bt6hk5xdq007pwfpa9gg/TINHKHUYET-XUANKEN.mp3?rlkey=sdxlo5ic4j98j4722eb7a6q2u&st=tvd54dpw&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TINHKHUYET-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/8qsk0qr7wiw2qqzvafn0m/TINHKHUYET-LYRIC.lrc?rlkey=otygwuqnj2ptp9cmn0493z4ed&st=zhnbkztz&dl=0",
    },
    {
        ID: "NBE",
        NAME: "Ngồi Bên Em",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGOIBENEM-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/s8vomb8b9qkb4pxo05lkw/NGOIBENEM-XUANKEN.mp3?rlkey=ckrqm58my2zx30jtoh74016nr&st=174y8syy&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGOIBENEM-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/23lkia7t8nknspw3zm05p/NGOIBENEM-LYRIC.lrc?rlkey=tbsdolda2noonuvsidqfg3btr&st=bxl13rbx&dl=0",
    },
    {
        ID: "TDTNNU",
        NAME: "Tiêu Dao Tuyệt Nhất (Ver Nữ)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TIEUDAOTUYETNHATNU-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/0tyy5hyl9hkns6cvobb03/TIEUDAOTUYETNHATNU-XUANKEN.mp3?rlkey=9roii9h3gkytex2pnoeksdgqq&st=zdoy5osc&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TIEUDAOTUYETNHATNU-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/hmls3nskxewi4fgszinzs/TIEUDAOTUYETNHATNU-LYRIC.lrc?rlkey=d1a9tcjge0s218a7waa59rl14&st=2m9dhq66&dl=0",
    },
    {
        ID: "TDTNNA",
        NAME: "Tiêu Dao Tuyệt Nhất (Ver Nam)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TIEUDAOTUYETNHATNAM-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/nh33b9axnj1y96hbhh0a6/TIEUDAOTUYETNHATNAM-XUANKEN.mp3?rlkey=u0zdtwjtb6rqrxkahnmd65kl4&st=3twzmajs&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TIEUDAOTUYETNHATNAM-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/5uum3n2dcygoazrm1cnpg/TIEUDAOTUYETNHATNAM-LYRIC.lrc?rlkey=b3sax386efgaw29c54k1enbmy&st=gj4ekfmo&dl=0",
    },
    {
        ID: "NOLGMRMKV1",
        NAME: "Người Ở Lại Giữa Mưa (Remake Ver 1)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIOLAIGIUAMUAREMAKEV1-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/kzni0ydqg9oz3jhx1uwqk/NGUOIOLAIGIUAMUAREMAKEV1-XUANKEN.mp3?rlkey=jqfu9s1cby32fs0hle84kg3sh&st=blh7btoe&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIOLAIGIUAMUAREMAKEV1-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/8rlk66u124razfy6f8g6h/NGUOIOLAIGIUAMUAREMAKEV1-LYRIC.lrc?rlkey=juydo44djv0aptt6388gerss9&st=ot3phz41&dl=0",
    },
    {
        ID: "NOLGMRMKV2",
        NAME: "Người Ở Lại Giữa Mưa (Remake Ver 2)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIOLAIGIUAMUAREMAKEV2-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/ixbpwnn3jddznqyh8wvei/NGUOIOLAIGIUAMUAREMAKEV2-XUANKEN.mp3?rlkey=svhrxdpvn3aome0eqw7o9hehd&st=5a3a7uvg&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIOLAIGIUAMUAREMAKEV2-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/jj0oliosgludioyiri723/NGUOIOLAIGIUAMUAREMAKEV2-LYRIC.lrc?rlkey=f8exd1xgq3dy21a0uefx9dviq&st=leo81ik9&dl=0",
    },
    {
        ID: "SCMLNNRMK",
        NAME: "Sau Cơn Mưa Là Nỗi Nhớ (Remake)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAUCONMUALANOINHOREMAKE-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/4nhyf9wfo22zcf8kepvos/SAUCONMUALANOINHOREMAKE-XUANKEN.mp3?rlkey=qnn35aewi5kkbz8iesz6dyyev&st=qzktv3d1&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAUCONMUALANOINHOREMAKE-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/pyh5uylkg4w725c50rn4h/SAUCONMUALANOINHOREMAKE-LYRIC.lrc?rlkey=e9ftz6mrgq4yqztbivtmy13ff&st=jqmmi5vr&dl=0",
    },
    {
        ID: "GNNKERMK",
        NAME: "Giữa Những Ngày Không Em (Remake)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/GIUANHUNGNGAYKHONGEMREMAKE-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/6zuwv2yodirdkjvim82vt/GIUANHUNGNGAYKHONGEMREMAKE-XUANKEN.mp3?rlkey=iherk1r703qn5tqth0trrlc2x&st=0epeuuql&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/GIUANHUNGNGAYKHONGEMREMAKE-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/95wabqgo2bj4gkd6z1e2i/GIUANHUNGNGAYKHONGEMREMAKE-LYRIC.lrc?rlkey=t9na3klvqgxck3p1f57tqjqgf&st=ubg1vjzv&dl=0",
    },
    {
        ID: "DCVLARMK",
        NAME: "Đến Cuối Vẫn Là Anh (Remake)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DENCUOIVANLAANHREMAKE-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/c8hf7evi016i7alew1xz0/DENCUOIVANLAANHREMAKE-XUANKEN.mp3?rlkey=nlnsdomphrlv3ste7xbofhm3u&st=b3l7wdlo&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DENCUOIVANLAANHREMAKE-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "LNUA",
        NAME: "Lo Người Ướt Áo",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/LONGUOIUOTAO-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/m5y2g1dg6zyyyjejvmkab/LONGUOIUOTAO-XUANKEN.mp3?rlkey=dtx7v8qbzz5kwroqb70rxbf8k&st=al9tsqi6&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/LONGUOIUOTAO-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "CVTY",
        NAME: "Cầu Vồng Tình Yêu",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CAUVONGTINHYEU-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/cuei0bsf4ytosz2ylxc4w/CAUVONGTINHYEU-XUANKEN.mp3?rlkey=0kd5k7wmyqxqdm9ke0gamgafu&st=wvyrs5jj&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CAUVONGTINHYEU-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "MCTETD",
        NAME: "Mỉm Cười Trông Em Thật Đẹp",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/MIMCUOITRONGEMTHATDEP-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/9o84fhb69n8hf8lvdl4o7/MIMCUOITRONGEMTHATDEP-XUANKEN.mp3?rlkey=z8y7eo5n3gdfkagq0biwptu3x&st=nms6ahbn&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/MIMCUOITRONGEMTHATDEP-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "CEHP",
        NAME: "Chúc Em Hạnh Phúc",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHUCEMHANHPHUC-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/0h0msp09nb4p3y7emkok6/CHUCEMHANHPHUC-XUANKEN.mp3?rlkey=ajwjfdvotwpnk1c5gos4mbrdm&st=mkqi288c&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHUCEMHANHPHUC-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "SNLPV",
        NAME: "Sinh Nhật Là Phải Vui",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SINHNHATLAPHAIVUI-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/nsgmll1afh3kv7y9wzcm1/SINHNHATLAPHAIVUI-XUANKEN.mp3?rlkey=f0ko1d7ljwurgywgseuqi7j12&st=c779fwr1&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SINHNHATLAPHAIVUI-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/kcvy5md9s3unktrdcqb3u/SINHNHATLAPHAIVUI-LYRIC.lrc?rlkey=mtfmy4ojc1hyayck23l68pwek&st=ji3qirzg&dl=0",
    },
    {
        ID: "SLTB",
        NAME: "Sau Lời Tạm Biệt",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAULOITAMBIET-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/p524zta5w1bgjtvib9m7p/SAULOITAMBIET-XUANKEN.mp3?rlkey=tvmpqbysyztan8p8fc6qh5g7p&st=vo0z8tk1&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAULOITAMBIET-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/ur3cyl6i7u4c52o1fqyil/SAULOITAMBIET-LYRIC.lrc?rlkey=ws6mpq9vfqtquec85nrnpdfnz&st=5hc55xk2&dl=0",
    },
    {
        ID: "MQVG",
        NAME: "Món Quà Vô Giá",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/MONQUAVOGIA-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/fuijf7q8htphn9q4x142t/MONQUAVOGIA-XUANKEN.mp3?rlkey=q6wrw8w2naxqf332lz4u25pee&st=nla1ou45&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/MONQUAVOGIA-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "BGNH",
        NAME: "Bay Giữa Ngân Hà",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/BAYGIUANGANHA-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/d40siu3rpo5k50r85jdwj/BAYGIUANGANHA-XUANKEN.mp3?rlkey=xqnqr2vc0yvbltpbyre5z2zfa&st=wvuxajfp&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/BAYGIUANGANHA-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "TLTXCN",
        NAME: "Từng Là Thanh Xuân Của Nhau",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TUNGLATHANHXUANCUANHAU-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/5q563c9qerc5434o50dwg/TUNGLATHANHXUANCUANHAU-XUANKEN.mp3?rlkey=22c5bqupw97ymipvioe8z3yp0&st=s6wg975g&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TUNGLATHANHXUANCUANHAU-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "CTDT",
        NAME: "Chúng Ta Đã Từng",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHUNGTADATUNG-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/pbh030k959oq9jibxu44h/CHUNGTADATUNG-XUANKEN.mp3?rlkey=05ntd1u16dfg36a1lctlb4b3e&st=u211mia2&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHUNGTADATUNG-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/rblqzx0aue2cpdyqx4p6r/CHUNGTADATUNG-LYRIC.lrc?rlkey=rv6hsjb8xs471pdi8kjvbkpcv&st=ggs9o8i9&dl=0",
    },
    {
        ID: "NBTRMK",
        NAME: "Nếu Biết Trước (Remake)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NEUBIETTRUOCREMAKE-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/jk1do59a9y710t9iby1uf/NEUBIETTRUOCREMAKE-XUANKEN.mp3?rlkey=vtcvevpxz0ku0yrk9cv2l6hwl&st=2ucy8oof&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NEUBIETTRUOCREMAKE-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "NNNA",
        NAME: "Ngày Này Năm Ấy",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGAYNAYNAMAY-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/ms2ebmosb41xcjkbjmg2j/NGAYNAYNAMAY-XUANKEN.mp3?rlkey=ehv6hgm9wgqjuqjti54piua6l&st=1kfaqh3c&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGAYNAYNAMAY-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "NEQG",
        NAME: "Ngày Em Quay Gót",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGAYEMQUAYGOT-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/kayhesf7xvbvbqx2iw1wo/NGAYEMQUAYGOT-XUANKEN.mp3?rlkey=zirwtjow4nx5ddz9xt5bkw6l6&st=mh8hxs2i&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGAYEMQUAYGOT-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "VNRDLE",
        NAME: "Vì Người Ra Đi Là Em",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/VINGUOIRADILAEM-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/9qbk0s9agvhhr4gzre15m/VINGUOIRADILAEM-XUANKEN.mp3?rlkey=bcguhrvkkxv9pdu7pol3p2tjz&st=2og14eyw&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/VINGUOIRADILAEM-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/c478s987xwx6k4f9tb37d/VINGUOIRADILAEM-LYRIC.lrc?rlkey=4652or6rx9oj6ak35pc5s42r7&st=fxhbtizh&dl=0",
    },
    {
        ID: "CCNNRMKV1",
        NAME: "Chỉ Còn Nỗi Nhớ (Remake Ver 1)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHICONNOINHOREMAKEV1-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/6ylespkgm17zoaqe89j3g/CHICONNOINHOREMAKEV1-XUANKEN.mp3?rlkey=wo0af4fqp1emtwj03r0k0q8lc&st=2ea7lgff&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHICONNOINHOREMAKEV1-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "CCNNRMKV2",
        NAME: "Chỉ Còn Nỗi Nhớ (Remake Ver 2)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHICONNOINHOREMAKEV2-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/soy9hnrqj9mqzboph8nn5/CHICONNOINHOREMAKEV2-XUANKEN.mp3?rlkey=mlabu6v4daiy1q43kj0tlh2v4&st=q79kf540&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHICONNOINHOREMAKEV2-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "DPMN",
        NAME: "Đơn Phương Một Người",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DONPHUONGMOTNGUOI-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/3ktypmo1ftdnjxaa84e7h/DONPHUONGMOTNGUOI-XUANKEN.mp3?rlkey=jgwio31idqud4mom5i8mue10i&st=yxks3kgc&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DONPHUONGMOTNGUOI-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/p8gi1tzpugtvta6gvcqnh/DONPHUONGMOTNGUOI-LYRIC.lrc?rlkey=023nlk6a33yx55i3fa2tct8iy&st=zjktykqb&dl=0",
    },
    {
        ID: "CCNN",
        NAME: "Chỉ Còn Nỗi Nhớ",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHICONNOINHO-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/197mae593vqipfshuwu3x/CHICONNOINHO-XUANKEN.mp3?rlkey=eps4a17ngxlhz98km8hl2phf9&st=rb600bpk&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHICONNOINHO-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/77klwvhih03qhxxza9yoy/CHICONNOINHO-LYRIC.lrc?rlkey=liv5eucci89rvk0mclj7jtzop&st=8guu545d&dl=0",
    },
    {
        ID: "GHNLCDRMK",
        NAME: "Giữa Hai Người Là Cô Đơn (Remake)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/GIUAHAINGUOILACODONREMAKE-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/mzi3avqtbr1cxd5q7n03g/GIUAHAINGUOILACODONREMAKE-XUANKEN.mp3?rlkey=k77daaynowmhtu2opfbio0zek&st=xv6gcfr5&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/GIUAHAINGUOILACODONREMAKE-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "DPMNRMK",
        NAME: "Đơn Phương Một Người (Remake)",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DONPHUONGMOTNGUOIREMAKE-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/befh2irdosd1dk1vmpq7t/DONPHUONGMOTNGUOIREMAKE-XUANKEN.mp3?rlkey=zvphp93vybczs9e7xhx7k5rvw&st=8z4d8dok&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DONPHUONGMOTNGUOIREMAKE-LYRIC.lrc",
        LRC2: "",
    },
    {
        ID: "STNCC",
        NAME: "Sau Tin Nhắn Cuối Cùng",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAUTINNHANCUOICUNG-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/9nevndn6wzh8z2spcvpgp/SAUTINNHANCUOICUNG-XUANKEN.mp3?rlkey=purmnppzj3wah52dp9306wrn6&st=3vw7cw87&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAUTINNHANCUOICUNG-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/kpw3za8aamyzgy2wae54y/SAUTINNHANCUOICUNG-LYRIC.lrc?rlkey=egrmmb21whrfn5thbi7745nsj&st=lndcii2a&dl=0",
    },
    {
        ID: "TSS",
        NAME: "Tình Sao Sáng",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TINHSAOSANG-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/sbg25dfxn60grwq8v7wcl/TINHSAOSANG-XUANKEN.mp3?rlkey=3gamigtufozi4ufdxqr0rf6qy&st=m26c0piz&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TINHSAOSANG-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/rdey9p5j0xsdfor3oqhu2/TINHSAOSANG-LYRIC.lrc?rlkey=3p0v13yiq1lyj9b7ksv847ol8&st=ezf7sk50&dl=0",
    },
    {
        ID: "GNNKE",
        NAME: "Giữa Những Ngày Không Em",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/GIUANHUNGNGAYKHONGEM-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/yfpkpk6x5sntn3q18k4bg/GIUANHUNGNGAYKHONGEM-XUANKEN.mp3?rlkey=tx02f10pgseknd8hqybavj8mq&st=x68ztpnu&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/GIUANHUNGNGAYKHONGEM-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/9h9qeez5okzgjcyjoji5z/GIUANHUNGNGAYKHONGEM-LYRIC.lrc?rlkey=20un4zy9pw1gp9qh2waobdm95&st=kzl2qs0x&dl=0",
    },
    {
        ID: "YLPZ",
        NAME: "Yêu Là Phải Zui",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/YEULAPHAIZUI-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/iz9lvg1uc9nj6z62kkvlz/YEULAPHAIZUI-XUANKEN.mp3?rlkey=1m8u4dtg8qg70ba7w7ecguqm8&st=yctumrd3&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/YEULAPHAIZUI-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/n208942x1ofwiy4xos5po/YEULAPHAIZUI-LYRIC.lrc?rlkey=xhn6q2alzuptj5n7z4kz73m8e&st=paxd0uox&dl=0",
    },
    {
        ID: "THST",
        NAME: "Thiệp Hồng Sai Tên",
        AUDIO1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/THIEPHONGSAITEN-XUANKEN.mp3",
        AUDIO2: "https://dl.dropboxusercontent.com/scl/fi/42es0vmuhckdse7oxxj4u/THIEPHONGSAITEN-XUANKEN.mp3?rlkey=eeld1muhae0oev2g73doq8s5v&st=59ckk7sr&dl=0",
        LRC1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/THIEPHONGSAITEN-LYRIC.lrc",
        LRC2: "https://dl.dropboxusercontent.com/scl/fi/mphx8b47rgfe3eewq42r9/THIEPHONGSAITEN-LYRIC.lrc?rlkey=u8jrdm5bn40ozpihe1waka9gu&st=y30zsdv9&dl=0",
    },
];
