const songs = [
    {
        id: "NEVQ",
        name: "Ngày Em Vu Quy",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGAYEMVUQUY-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/2ix1ns96v8qc26fyizvm7/NGAYEMVUQUY-XUANKEN.mp3?rlkey=hw5ro0z9pgg4qua16ys6ofrtk&st=st9ckyf3&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGAYEMVUQUY-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/vd8p2aztg2oqgwvan49nh/NGAYEMVUQUY-LYRIC.lrc?rlkey=e80y122dz8ge8y60tz0e12fry&st=plt9z1sw&dl=0",
    },
    {
        id: "TTLBAN",
        name: "Thất Tình & Làm Bạn Anh Nhé (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/THATTINHLAMBANANHNHE-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/g4k5j0x9j0bbfvt3eta9t/THATTINHLAMBANANHNHE-XUANKEN.mp3?rlkey=h1s2unsb9n0ii3poub0eu43u6&st=dbwmvk8z&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/THATTINHLAMBANANHNHE-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/6bm5qyx5t5a7fq6n68p3r/THATTINHLAMBANANHNHE-LYRIC.lrc?rlkey=3hop1nkywgwso083mdwltv7z2&st=o8nh6zok&dl=0",
    },
    {
        id: "QNDN",
        name: "Quên Nhau Đi Nhé (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/QUENNHAUDINHE-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/y7oitkaozlf1tk1bp2lh1/QUENNHAUDINHE-XUANKEN.mp3?rlkey=y3pb2acbc5db4rgnkzdmu3bb3&st=8c1hu39q&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/QUENNHAUDINHE-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/58jy9lgo054nhgybeowpu/QUENNHAUDINHE-LYRIC.lrc?rlkey=sdsf40n4a0nddbhqpctgb2ob0&st=8ckarrkq&dl=0",
    },
    {
        id: "AME",
        name: "Ánh Mắt Em",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/ANHMATEM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/bjxmvn0nk43h81w1y6r8a/ANHMATEM-XUANKEN.mp3?rlkey=4tzanju49d63qkc27cdziu51g&st=mvrnng6s&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/ANHMATEM-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/re28enq6huuyhkibdyxq6/ANHMATEM-LYRIC.lrc?rlkey=5t87c99zogg7q5a3ugss02n0u&st=fnfjr5zq&dl=0",
    },
    {
        id: "DEBNK",
        name: "Để Em Bên Người Khác",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DEEMBENNGUOIKHAC-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/bco0g3mdeiwrjsmyqsyv6/DEEMBENNGUOIKHAC-XUANKEN.mp3?rlkey=9gto06vls3tcnc92mn050qex2&st=042c9xjv&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DEEMBENNGUOIKHAC-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/sdw6mh5s2jbo4fmv5sjqr/DEEMBENNGUOIKHAC-LYRIC.lrc?rlkey=9ztqriimvtc3dp2x9kh536ayu&st=j0wuhpoh&dl=0",
    },
    {
        id: "NOLTT",
        name: "Người Ở Lại Trong Tim",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIOLAITRONGTIM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/glwck81hgjka16k9q183l/NGUOIOLAITRONGTIM-XUANKEN.mp3?rlkey=i3p7j7tr4dkpzfpo1oyz0z79h&st=mrzm37ux&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIOLAITRONGTIM-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/nk7f9jnzixbckjxur6wiw/NGUOIOLAITRONGTIM-LYRIC.lrc?rlkey=ftjbip4j30voaiyptthhkq4hn&st=uz38oyzp&dl=0",
    },
    {
        id: "DEMR",
        name: "Dính Em Mất Rồi",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DINHEMMATROI-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/cfqtazmwwi5uetvuz8sgk/DINHEMMATROI-XUANKEN.mp3?rlkey=k48q2oh8gof6da5gkqnp55n1v&st=6jssy0zf&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DINHEMMATROI-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/l34neac0q9979eba51trr/DINHEMMATROI-LYRIC.lrc?rlkey=c14ci8ghv3ukslx30ngso68be&st=8xrbs75m&dl=0",
    },
    {
        id: "SCMLNN",
        name: "Sau Cơn Mưa Là Nỗi Nhớ",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAUCONMUALANOINHO-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/ybt4ie8n1rkvodpzanz37/SAUCONMUALANOINHO-XUANKEN.mp3?rlkey=hqqplne8gn0pz5mpbo464m9sw&st=57lmttit&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAUCONMUALANOINHO-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/qh2y72mmiazu8zg81490p/SAUCONMUALANOINHO-LYRIC.lrc?rlkey=z1mtyfuta0jv2j16fypkfh8za&st=3ulsx4em&dl=0",
    },
    {
        id: "NOLGM",
        name: "Người Ở Lại Giữa Mưa",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIOLAIGIUAMUA-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/g4x7mxd3q00pntnxgwzp9/NGUOIOLAIGIUAMUA-XUANKEN.mp3?rlkey=s1pe96tibyiwp1eq8krv12t0z&st=g22qdfog&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIOLAIGIUAMUA-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/qjseeej3866khpdn5jh3q/NGUOIOLAIGIUAMUA-LYRIC.lrc?rlkey=mqsly2tfhzk3ejlorry7gbxb2&st=u4ajumn2&dl=0",
    },
    {
        id: "GHNLCD",
        name: "Giữa Hai Người Là Cô Đơn",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/GIUAHAINGUOILACODON-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/uv8e3378ffc2vpc4vimc4/GIUAHAINGUOILACODON-XUANKEN.mp3?rlkey=crnbvb9vktzozmt0940ubhusw&st=817tfrhc&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/GIUAHAINGUOILACODON-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/50zvqzbm7qjcc80q4ajv3/GIUAHAINGUOILACODON-LYRIC.lrc?rlkey=rif6162gbidnq1z60kojcl515&st=ch0uu30y&dl=0",
    },
    {
        id: "CTDLOD",
        name: "Chúng Ta Dừng Lại Ở Đây",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHUNGTADUNGLAIODAY-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/xf7ctz25m23af8fmpcjdc/CHUNGTADUNGLAIODAY-XUANKEN.mp3?rlkey=62mr2hadwouba3vyts6us548e&st=k7efytfj&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHUNGTADUNGLAIODAY-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/zt6uwa21nj4a7rf2yl5yk/CHUNGTADUNGLAIODAY-LYRIC.lrc?rlkey=1tdkw5gllx62rddklruznn0xf&st=2tkdiozi&dl=0",
    },
    {
        id: "DCVLA",
        name: "Đến Cuối Vẫn Là Anh",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DENCUOIVANLAANH-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/k1df0ha02l6cu7zj71ez0/DENCUOIVANLAANH-XUANKEN.mp3?rlkey=51o310ybx6oooatdw4fyc2y1e&st=kanurgew&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DENCUOIVANLANH-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/owe5ld6aghuml5gejonxh/DENCUOIVANLANH-LYRIC.lrc?rlkey=gghijpfo7ijmvnzki5j33celt&st=iwwwc0fe&dl=0",
    },
    {
        id: "VQNVT",
        name: "Về Quảng Ninh Với Tôi",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/VEQUANGNINHVOITOI-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/f306jvn3vl4p5cwygptdu/VEQUANGNINHVOITOI-XUANKEN.mp3?rlkey=36e07p5u5olykp6u3ygdzwtbf&st=fqgorzn7&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/VEQUANGNINHVOITOI-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/yjeve4nfqbvpos32vnztd/VEQUANGNINHVOITOI-LYRIC.lrc?rlkey=mwck80s4qzbjoukcmlsdblzsj&st=108lsdsf&dl=0",
    },
    {
        id: "AYESTD",
        name: "Anh Yêu Em Sai Thời Điểm (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/ANHYEUEMSAITHOIDIEM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/4i6cgievzz4iv63p9maze/ANHYEUEMSAITHOIDIEM-XUANKEN.mp3?rlkey=2akpj5xnjg9q2gi2pqosabm81&st=lkr9n1i5&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/ANHYEUEMSAITHOIDIEM-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/s5517uy35ox6el8z10im9/ANHYEUEMSAITHOIDIEM-LYRIC.lrc?rlkey=w63rlr78wr0ai9iwuonsxoovq&st=a3kkuixr&dl=0",
    },
    {
        id: "DCTHP",
        name: "Đợi Chờ Trong Hạnh Phúc (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DOICHOTRONGHANHPHUC-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/i6knkkziozjb96llznl5x/DOICHOTRONGHANHPHUC-XUANKEN.mp3?rlkey=jn2bc2nou1kq9p61gpddtw9cx&st=w8o50bm3&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DOICHOTRONGHANHPHUC-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/ic1tvdnvo72f0oglk4s0l/DOICHOTRONGHANHPHUC-LYRIC.lrc?rlkey=cs5c4hru19ngxpzeoxn8b1w2j&st=o0bct67o&dl=0",
    },
    {
        id: "ECLBT",
        name: "Em Chỉ Là Bạn Thân (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/EMCHILABANTHAN-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/g4wy0ph5xbw1xe6jiloxs/EMCHILABANTHAN-XUANKEN.mp3?rlkey=1nvjs671dua8vs5998j0l5u9e&st=hmcwhswl&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/EMCHILABANTHAN-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/3b7g06t00gbnfb2lyldkx/EMCHILABANTHAN-LYRIC.lrc?rlkey=r1z5dw8n21j5dton39kbe0dkj&st=fobw0zmd&dl=0",
    },
    {
        id: "KHI",
        name: "Khi (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/KHI-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/zhpyu4foriy96avkvtx5t/KHI-XUANKEN.mp3?rlkey=3a3tqb62axoqwnszc340j3c11&st=pmyh4n6c&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/KHI-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/3sia20fm98mzwpy5oomrq/KHI-LYRIC.lrc?rlkey=j0uit3g16nfjatkt8vdsdzsd8&st=kagj33fn&dl=0",
    },
    {
        id: "CTLBV1",
        name: "Chuyến Tàu Ly Biệt (Version 1) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHUYENTAULYBIETV1-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/itwl4qmf52swpx16zpuiw/CHUYENTAULYBIETV1-XUANKEN.mp3?rlkey=uug7me80pghelshev8alzy1mr&st=yhg50rjx&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHUYENTAULYBIETV1-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/8aql77b6gu8vhgg5mlc3o/CHUYENTAULYBIETV1-LYRIC.lrc?rlkey=a7w0qp5n7qzztu8nevhwkptnn&st=56mijmwo&dl=0",
    },
    {
        id: "CTLBV2",
        name: "Chuyến Tàu Ly Biệt (Version 2) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHUYENTAULYBIETV2-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/6si135ztin6lcxiaxjthn/CHUYENTAULYBIETV2-XUANKEN.mp3?rlkey=g0hnxr8pbemyv782edmeuvxhb&st=rzq1ianv&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHUYENTAULYBIETV2-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/94g0rzxtzw3g49dxrfpws/CHUYENTAULYBIETV2-LYRIC.lrc?rlkey=xvxa50qb8yt9hc0j1tp74dui1&st=ub7p1t5u&dl=0",
    },
    {
        id: "50NVS",
        name: "50 Năm Về Sau (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/50NAMVESAU-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/gx7lmver0no1ds2fg7xq3/50NAMVESAU-XUANKEN.mp3?rlkey=o3hrdj1nfkmts6nyll9gr6m8e&st=c3juscsq&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/50NAMVESAU-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/shskp35a337ofgyc3lzss/50NAMVESAU-LYRIC.lrc?rlkey=esgzd3ou6z3w8n5xk8c8k7min&st=2eqqh9ha&dl=0",
    },
    {
        id: "PCCENA",
        name: "Phố Cũ Còn Em (Version Nam) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/PHOCUCONEM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/hdhgb71qdnb8umpikx2zc/PHOCUCONEM-XUANKEN.mp3?rlkey=4antz9cak1qomr5a388ufpnwg&st=1p432yqb&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/PHOCUCONEM-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/tsmlyaonhe1tpupc03vfk/PHOCUCONEM-LYRIC.lrc?rlkey=ll8sfbadhxt6wgezf54redbw9&st=dg2ghga9&dl=0",
    },
    {
        id: "PCCANU",
        name: "Phố Cũ Còn Anh (Version Nữ) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/PHOCUCONANH-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/ecd36mpc0fwln8uayf1ob/PHOCUCONANH-XUANKEN.mp3?rlkey=a6cgjphx3k835fj0bsez7q0n0&st=thwtxs8o&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/PHOCUCONANH-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/r7hz6azahisadc6fkmkji/PHOCUCONANH-LYRIC.lrc?rlkey=7tffm91ckfczqll8vb9ty27hd&st=rpvcyswq&dl=0",
    },
    {
        id: "NKOL",
        name: "Người Không Ở Lại",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIKHONGOLAI-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/8abmzuqfakf6fbdkg24hf/NGUOIKHONGOLAI-XUANKEN.mp3?rlkey=070shp3aupj7c279ohptidcqj&st=oox5m476&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIKHONGOLAI-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/tn7hynsb1hi2galaid4cq/NGUOIKHONGOLAI-LYRIC.lrc?rlkey=za2vc3txmkxlqjqw16dkdp9hv&st=gyzupiuo&dl=0",
    },
    {
        id: "MLVA",
        name: "Mở Lòng Vì Ai (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/MOLONGVIAI-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/2zd1wjb03tb3k3ba0z3ds/MOLONGVIAI-XUANKEN.mp3?rlkey=6fauh5zswmdgf1zojg8ktoo4w&st=ap5i0b5z&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/MOLONGVIAI-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/3lct6f7oov7nwcfwbb540/MOLONGVIAI-LYRIC.lrc?rlkey=2zzhdyuahqvpiv93lfcsd64vr&st=8rgkp4ve&dl=0",
    },
    {
        id: "ATAT",
        name: "Anh Thua Anh Ta (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/ANHTHUAANHTA-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/l9xefrqht2xroh0zvkh3m/ANHTHUAANHTA-XUANKEN.mp3?rlkey=gq3iu0xjycimmsfm4vzedusl4&st=e2jt4ybw&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/ANHTHUAANHTA-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "CCNNNU",
        name: "Có Chút Ngọt Ngào (Version Nữ) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/COCHUTNGOTNGAONU-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/jj0rfg3hgn29kan17yw3d/COCHUTNGOTNGAONU-XUANKEN.mp3?rlkey=sl25xj6o977i4ec9r12hfsfon&st=8j4svwjf&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/COCHUTNGOTNGAONU-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/nu9fvjej9alp5jer9uvqg/COCHUTNGOTNGAONAM-LYRIC.lrc?rlkey=gqkp0rkh4h4bdxxx5ls4v71vy&st=2nk8cgxt&dl=0",
    },
    {
        id: "CCNNNA",
        name: "Có Chút Ngọt Ngào (Version Nam) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/COCHUTNGOTNGAONAM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/ia8dyq8rsc98fikfce0zr/COCHUTNGOTNGAONAM-XUANKEN.mp3?rlkey=6zknjbdoglz86pga5k2zy45wz&st=e2hjfkdg&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/COCHUTNGOTNGAONAM-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/nu9fvjej9alp5jer9uvqg/COCHUTNGOTNGAONAM-LYRIC.lrc?rlkey=gqkp0rkh4h4bdxxx5ls4v71vy&st=2nk8cgxt&dl=0",
    },
    {
        id: "BTTTNU",
        name: "Bên Tách Trà Thơm (Version Nữ) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/BENTACHTRATHOMNU-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/xmvov370ukauo6onn1gf2/BENTACHTRATHOMNU-XUANKEN.mp3?rlkey=zfuts0yscqqvts6v7s7g0xqv8&st=9ojbt0lw&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/BENTACHTRATHOMNU-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/ulqccle4hse176qc747pj/BENTACHTRATHOMNU-LYRIC.lrc?rlkey=yanwbm67t0pxur4hgosw6klvp&st=xm8t9vcv&dl=0",
    },
    {
        id: "BTTTNA",
        name: "Bên Tách Trà Thơm (Version Nam) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/BENTACHTRATHOMNAM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/am7ldgzplcftj3y27lnod/BENTACHTRATHOMNAM-XUANKEN.mp3?rlkey=et4mpw2qixg2ve7dzsw4k3dlt&st=y2g4vw76&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/BENTACHTRATHOMNAM-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/8w2l5akni8rvqtn1vlljk/BENTACHTRATHOMNAM-LYRIC.lrc?rlkey=yt8a0sdi0uo7ywhjrmel48euz&st=wzntz7xo&dl=0",
    },
    {
        id: "CON",
        name: "Cảm Ơn Nhé (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CAMONNHE-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/8nippzv9z1tpz8cyg3ut0/CAMONNHE-XUANKEN.mp3?rlkey=p2mbpeguwmyoeyqmvh0nqey9g&st=bav6msre&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CAMONNHE-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/xp3i60cp7drktyh3eogw0/CAMONNHE-LYRIC.lrc?rlkey=xskite6tijtlqqydpi5bsd1v9&st=m04xm21l&dl=0",
    },
    {
        id: "SLH",
        name: "Sau Lời Hứa",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAULOIHUA-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/qiduzyfsjh7vvgvhgpdo4/SAULOIHUA-XUANKEN.mp3?rlkey=gov4w3tm22y5xdnin806niyc7&st=vy0hfcl1&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAULOIHUA-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/tiunqs1qhabr74w3bz4th/SAULOIHUA-LYRIC.lrc?rlkey=ynkwurnc3kltl30g442fwfcmb&st=ozlkxqj5&dl=0",
    },
    {
        id: "TK",
        name: "Tình Khuyết (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TINHKHUYET-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/4bt6hk5xdq007pwfpa9gg/TINHKHUYET-XUANKEN.mp3?rlkey=sdxlo5ic4j98j4722eb7a6q2u&st=tvd54dpw&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TINHKHUYET-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/8qsk0qr7wiw2qqzvafn0m/TINHKHUYET-LYRIC.lrc?rlkey=otygwuqnj2ptp9cmn0493z4ed&st=zhnbkztz&dl=0",
    },
    {
        id: "NBEV1",
        name: "Ngồi Bên Em (Version 1) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGOIBENEM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/s8vomb8b9qkb4pxo05lkw/NGOIBENEM-XUANKEN.mp3?rlkey=ckrqm58my2zx30jtoh74016nr&st=174y8syy&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGOIBENEM-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/23lkia7t8nknspw3zm05p/NGOIBENEM-LYRIC.lrc?rlkey=tbsdolda2noonuvsidqfg3btr&st=bxl13rbx&dl=0",
    },
    {
        id: "NBEV2",
        name: "Ngồi Bên Em (Version 2) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGOIBENEMV2-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/euu0mvsgw385dihr3uda5/NGOIBENEMV2-XUANKEN.mp3?rlkey=m40usy5n75sc5b5lgzbg36wgo&st=qmkii1fg&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGOIBENEMV2-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/rtmr00xm42t1gv73z7qal/NGOIBENEMV2-LYRIC.lrc?rlkey=uf2vyx9ljt110z9ib4m9rjgkr&st=q9pv2e10&dl=0",
    },
    {
        id: "TDTNNU",
        name: "Tiêu Dao Tuyệt Nhất (Version Nữ) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TIEUDAOTUYETNHATNU-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/0tyy5hyl9hkns6cvobb03/TIEUDAOTUYETNHATNU-XUANKEN.mp3?rlkey=9roii9h3gkytex2pnoeksdgqq&st=zdoy5osc&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TIEUDAOTUYETNHATNU-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/hmls3nskxewi4fgszinzs/TIEUDAOTUYETNHATNU-LYRIC.lrc?rlkey=d1a9tcjge0s218a7waa59rl14&st=2m9dhq66&dl=0",
    },
    {
        id: "TDTNNA",
        name: "Tiêu Dao Tuyệt Nhất (Version Nam) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TIEUDAOTUYETNHATNAM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/nh33b9axnj1y96hbhh0a6/TIEUDAOTUYETNHATNAM-XUANKEN.mp3?rlkey=u0zdtwjtb6rqrxkahnmd65kl4&st=3twzmajs&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TIEUDAOTUYETNHATNAM-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/5uum3n2dcygoazrm1cnpg/TIEUDAOTUYETNHATNAM-LYRIC.lrc?rlkey=b3sax386efgaw29c54k1enbmy&st=gj4ekfmo&dl=0",
    },
    {
        id: "NOLGMRMKV1",
        name: "Người Ở Lại Giữa Mưa (Remake Version 1)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIOLAIGIUAMUAREMAKEV1-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/kzni0ydqg9oz3jhx1uwqk/NGUOIOLAIGIUAMUAREMAKEV1-XUANKEN.mp3?rlkey=jqfu9s1cby32fs0hle84kg3sh&st=blh7btoe&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIOLAIGIUAMUAREMAKEV1-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/8rlk66u124razfy6f8g6h/NGUOIOLAIGIUAMUAREMAKEV1-LYRIC.lrc?rlkey=juydo44djv0aptt6388gerss9&st=ot3phz41&dl=0",
    },
    {
        id: "NOLGMRMKV2",
        name: "Người Ở Lại Giữa Mưa (Remake Version 2)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIOLAIGIUAMUAREMAKEV2-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/ixbpwnn3jddznqyh8wvei/NGUOIOLAIGIUAMUAREMAKEV2-XUANKEN.mp3?rlkey=svhrxdpvn3aome0eqw7o9hehd&st=5a3a7uvg&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIOLAIGIUAMUAREMAKEV2-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/jj0oliosgludioyiri723/NGUOIOLAIGIUAMUAREMAKEV2-LYRIC.lrc?rlkey=f8exd1xgq3dy21a0uefx9dviq&st=leo81ik9&dl=0",
    },
    {
        id: "SCMLNNRMK",
        name: "Sau Cơn Mưa Là Nỗi Nhớ (Remake)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAUCONMUALANOINHOREMAKE-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/4nhyf9wfo22zcf8kepvos/SAUCONMUALANOINHOREMAKE-XUANKEN.mp3?rlkey=qnn35aewi5kkbz8iesz6dyyev&st=qzktv3d1&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAUCONMUALANOINHOREMAKE-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/pyh5uylkg4w725c50rn4h/SAUCONMUALANOINHOREMAKE-LYRIC.lrc?rlkey=e9ftz6mrgq4yqztbivtmy13ff&st=jqmmi5vr&dl=0",
    },
    {
        id: "GNNKERMK",
        name: "Giữa Những Ngày Không Em (Remake)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/GIUANHUNGNGAYKHONGEMREMAKE-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/6zuwv2yodirdkjvim82vt/GIUANHUNGNGAYKHONGEMREMAKE-XUANKEN.mp3?rlkey=iherk1r703qn5tqth0trrlc2x&st=0epeuuql&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/GIUANHUNGNGAYKHONGEMREMAKE-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/95wabqgo2bj4gkd6z1e2i/GIUANHUNGNGAYKHONGEMREMAKE-LYRIC.lrc?rlkey=t9na3klvqgxck3p1f57tqjqgf&st=ubg1vjzv&dl=0",
    },
    {
        id: "DCVLARMK",
        name: "Đến Cuối Vẫn Là Anh (Remake)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DENCUOIVANLAANHREMAKE-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/c8hf7evi016i7alew1xz0/DENCUOIVANLAANHREMAKE-XUANKEN.mp3?rlkey=nlnsdomphrlv3ste7xbofhm3u&st=b3l7wdlo&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DENCUOIVANLAANHREMAKE-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "LNUA",
        name: "Lo Người Ướt Áo (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/LONGUOIUOTAO-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/m5y2g1dg6zyyyjejvmkab/LONGUOIUOTAO-XUANKEN.mp3?rlkey=dtx7v8qbzz5kwroqb70rxbf8k&st=al9tsqi6&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/LONGUOIUOTAO-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "CVTY",
        name: "Cầu Vồng Tình Yêu (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CAUVONGTINHYEU-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/cuei0bsf4ytosz2ylxc4w/CAUVONGTINHYEU-XUANKEN.mp3?rlkey=0kd5k7wmyqxqdm9ke0gamgafu&st=wvyrs5jj&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CAUVONGTINHYEU-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "MCTETD",
        name: "Mỉm Cười Trông Em Thật Đẹp (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/MIMCUOITRONGEMTHATDEP-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/9o84fhb69n8hf8lvdl4o7/MIMCUOITRONGEMTHATDEP-XUANKEN.mp3?rlkey=z8y7eo5n3gdfkagq0biwptu3x&st=nms6ahbn&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/MIMCUOITRONGEMTHATDEP-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "CEHP",
        name: "Chúc Em Hạnh Phúc (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHUCEMHANHPHUC-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/0h0msp09nb4p3y7emkok6/CHUCEMHANHPHUC-XUANKEN.mp3?rlkey=ajwjfdvotwpnk1c5gos4mbrdm&st=mkqi288c&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHUCEMHANHPHUC-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "SNLPV",
        name: "Sinh Nhật Là Phải Vui",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SINHNHATLAPHAIVUI-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/nsgmll1afh3kv7y9wzcm1/SINHNHATLAPHAIVUI-XUANKEN.mp3?rlkey=f0ko1d7ljwurgywgseuqi7j12&st=c779fwr1&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SINHNHATLAPHAIVUI-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/kcvy5md9s3unktrdcqb3u/SINHNHATLAPHAIVUI-LYRIC.lrc?rlkey=mtfmy4ojc1hyayck23l68pwek&st=ji3qirzg&dl=0",
    },
    {
        id: "SLTB",
        name: "Sau Lời Tạm Biệt",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAULOITAMBIET-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/p524zta5w1bgjtvib9m7p/SAULOITAMBIET-XUANKEN.mp3?rlkey=tvmpqbysyztan8p8fc6qh5g7p&st=vo0z8tk1&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAULOITAMBIET-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/ur3cyl6i7u4c52o1fqyil/SAULOITAMBIET-LYRIC.lrc?rlkey=ws6mpq9vfqtquec85nrnpdfnz&st=5hc55xk2&dl=0",
    },
    {
        id: "MQVG",
        name: "Món Quà Vô Giá (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/MONQUAVOGIA-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/fuijf7q8htphn9q4x142t/MONQUAVOGIA-XUANKEN.mp3?rlkey=q6wrw8w2naxqf332lz4u25pee&st=nla1ou45&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/MONQUAVOGIA-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "BGNH",
        name: "Bay Giữa Ngân Hà (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/BAYGIUANGANHA-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/d40siu3rpo5k50r85jdwj/BAYGIUANGANHA-XUANKEN.mp3?rlkey=xqnqr2vc0yvbltpbyre5z2zfa&st=wvuxajfp&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/BAYGIUANGANHA-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "TLTXCN",
        name: "Từng Là Thanh Xuân Của Nhau (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TUNGLATHANHXUANCUANHAU-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/5q563c9qerc5434o50dwg/TUNGLATHANHXUANCUANHAU-XUANKEN.mp3?rlkey=22c5bqupw97ymipvioe8z3yp0&st=s6wg975g&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TUNGLATHANHXUANCUANHAU-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "CTDT",
        name: "Chúng Ta Đã Từng",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHUNGTADATUNG-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/pbh030k959oq9jibxu44h/CHUNGTADATUNG-XUANKEN.mp3?rlkey=05ntd1u16dfg36a1lctlb4b3e&st=u211mia2&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHUNGTADATUNG-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/rblqzx0aue2cpdyqx4p6r/CHUNGTADATUNG-LYRIC.lrc?rlkey=rv6hsjb8xs471pdi8kjvbkpcv&st=ggs9o8i9&dl=0",
    },
    {
        id: "NBTRMK",
        name: "Nếu Biết Trước (Remake)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NEUBIETTRUOCREMAKE-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/jk1do59a9y710t9iby1uf/NEUBIETTRUOCREMAKE-XUANKEN.mp3?rlkey=vtcvevpxz0ku0yrk9cv2l6hwl&st=2ucy8oof&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NEUBIETTRUOCREMAKE-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "NNNA",
        name: "Ngày Này Năm Ấy (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGAYNAYNAMAY-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/ms2ebmosb41xcjkbjmg2j/NGAYNAYNAMAY-XUANKEN.mp3?rlkey=ehv6hgm9wgqjuqjti54piua6l&st=1kfaqh3c&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGAYNAYNAMAY-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "NEQG",
        name: "Ngày Em Quay Gót (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGAYEMQUAYGOT-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/kayhesf7xvbvbqx2iw1wo/NGAYEMQUAYGOT-XUANKEN.mp3?rlkey=zirwtjow4nx5ddz9xt5bkw6l6&st=mh8hxs2i&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGAYEMQUAYGOT-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "VNRDLE",
        name: "Vì Người Ra Đi Là Em",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/VINGUOIRADILAEM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/9qbk0s9agvhhr4gzre15m/VINGUOIRADILAEM-XUANKEN.mp3?rlkey=bcguhrvkkxv9pdu7pol3p2tjz&st=2og14eyw&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/VINGUOIRADILAEM-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/c478s987xwx6k4f9tb37d/VINGUOIRADILAEM-LYRIC.lrc?rlkey=4652or6rx9oj6ak35pc5s42r7&st=fxhbtizh&dl=0",
    },
    {
        id: "CCNNRMKV1",
        name: "Chỉ Còn Nỗi Nhớ (Remake Version 1)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHICONNOINHOREMAKEV1-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/6ylespkgm17zoaqe89j3g/CHICONNOINHOREMAKEV1-XUANKEN.mp3?rlkey=wo0af4fqp1emtwj03r0k0q8lc&st=2ea7lgff&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHICONNOINHOREMAKEV1-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "CCNNRMKV2",
        name: "Chỉ Còn Nỗi Nhớ (Remake Version 2)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHICONNOINHOREMAKEV2-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/soy9hnrqj9mqzboph8nn5/CHICONNOINHOREMAKEV2-XUANKEN.mp3?rlkey=mlabu6v4daiy1q43kj0tlh2v4&st=q79kf540&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHICONNOINHOREMAKEV2-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "DPMN",
        name: "Đơn Phương Một Người",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DONPHUONGMOTNGUOI-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/3ktypmo1ftdnjxaa84e7h/DONPHUONGMOTNGUOI-XUANKEN.mp3?rlkey=jgwio31idqud4mom5i8mue10i&st=yxks3kgc&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DONPHUONGMOTNGUOI-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/p8gi1tzpugtvta6gvcqnh/DONPHUONGMOTNGUOI-LYRIC.lrc?rlkey=023nlk6a33yx55i3fa2tct8iy&st=zjktykqb&dl=0",
    },
    {
        id: "CCNN",
        name: "Chỉ Còn Nỗi Nhớ",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CHICONNOINHO-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/197mae593vqipfshuwu3x/CHICONNOINHO-XUANKEN.mp3?rlkey=eps4a17ngxlhz98km8hl2phf9&st=rb600bpk&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CHICONNOINHO-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/77klwvhih03qhxxza9yoy/CHICONNOINHO-LYRIC.lrc?rlkey=liv5eucci89rvk0mclj7jtzop&st=8guu545d&dl=0",
    },
    {
        id: "GHNLCDRMK",
        name: "Giữa Hai Người Là Cô Đơn (Remake)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/GIUAHAINGUOILACODONREMAKE-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/inhiow8lef3o7w1nbnmrj/GIUAHAINGUOILACODONREMAKE-XUANKEN.mp3?rlkey=q1itz3dylgrf9txvuqq7djirb&st=3m0tcrsw&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/GIUAHAINGUOILACODONREMAKE-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/7fdiko10szud1jp6wndeg/GIUAHAINGUOILACODONREMAKE-LYRIC.lrc?rlkey=xj3yka7axj19ux9jsfeza6zny&st=za4z120v&dl=0",
    },
    {
        id: "DPMNRMK",
        name: "Đơn Phương Một Người (Remake)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/DONPHUONGMOTNGUOIREMAKE-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/befh2irdosd1dk1vmpq7t/DONPHUONGMOTNGUOIREMAKE-XUANKEN.mp3?rlkey=zvphp93vybczs9e7xhx7k5rvw&st=8z4d8dok&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/DONPHUONGMOTNGUOIREMAKE-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "STNCC",
        name: "Sau Tin Nhắn Cuối Cùng",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAUTINNHANCUOICUNG-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/9nevndn6wzh8z2spcvpgp/SAUTINNHANCUOICUNG-XUANKEN.mp3?rlkey=purmnppzj3wah52dp9306wrn6&st=3vw7cw87&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAUTINNHANCUOICUNG-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/kpw3za8aamyzgy2wae54y/SAUTINNHANCUOICUNG-LYRIC.lrc?rlkey=egrmmb21whrfn5thbi7745nsj&st=lndcii2a&dl=0",
    },
    {
        id: "TSS",
        name: "Tình Sao Sáng (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TINHSAOSANG-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/sbg25dfxn60grwq8v7wcl/TINHSAOSANG-XUANKEN.mp3?rlkey=3gamigtufozi4ufdxqr0rf6qy&st=m26c0piz&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TINHSAOSANG-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/rdey9p5j0xsdfor3oqhu2/TINHSAOSANG-LYRIC.lrc?rlkey=3p0v13yiq1lyj9b7ksv847ol8&st=ezf7sk50&dl=0",
    },
    {
        id: "GNNKE",
        name: "Giữa Những Ngày Không Em",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/GIUANHUNGNGAYKHONGEM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/yfpkpk6x5sntn3q18k4bg/GIUANHUNGNGAYKHONGEM-XUANKEN.mp3?rlkey=tx02f10pgseknd8hqybavj8mq&st=x68ztpnu&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/GIUANHUNGNGAYKHONGEM-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/9h9qeez5okzgjcyjoji5z/GIUANHUNGNGAYKHONGEM-LYRIC.lrc?rlkey=20un4zy9pw1gp9qh2waobdm95&st=kzl2qs0x&dl=0",
    },
    {
        id: "YLPZ",
        name: "Yêu Là Phải Zui",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/YEULAPHAIZUI-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/iz9lvg1uc9nj6z62kkvlz/YEULAPHAIZUI-XUANKEN.mp3?rlkey=1m8u4dtg8qg70ba7w7ecguqm8&st=yctumrd3&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/YEULAPHAIZUI-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/n208942x1ofwiy4xos5po/YEULAPHAIZUI-LYRIC.lrc?rlkey=xhn6q2alzuptj5n7z4kz73m8e&st=paxd0uox&dl=0",
    },
    {
        id: "THST",
        name: "Thiệp Hồng Sai Tên (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/THIEPHONGSAITEN-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/42es0vmuhckdse7oxxj4u/THIEPHONGSAITEN-XUANKEN.mp3?rlkey=eeld1muhae0oev2g73doq8s5v&st=59ckk7sr&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/THIEPHONGSAITEN-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/mphx8b47rgfe3eewq42r9/THIEPHONGSAITEN-LYRIC.lrc?rlkey=u8jrdm5bn40ozpihe1waka9gu&st=y30zsdv9&dl=0",
    },
    {
        id: "NNSCH",
        name: "Những Ngôi Sao Cuối Hạ",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NHUNGNGOISAOCUOIHA-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/u70auyow58g8pv0tmr39v/NHUNGNGOISAOCUOIHA-XUANKEN.mp3?rlkey=b0nimcamzdaw0dbgcg9z05x5s&st=buwni24h&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NHUNGNGOISAOCUOIHA-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/jp2ljf5yy1vuwmh9yf7bn/NHUNGNGOISAOCUOIHA-LYRIC.lrc?rlkey=1ccm4c1b4naznd53zr6wntpmm&st=nj8re0r7&dl=0",
    },
    {
        id: "NXED",
        name: "Ngày Xưa Em Đến (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGAYXUAEMDEN-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/7nyeu5giunmvdbc74q8o2/NGAYXUAEMDEN-XUANKEN.mp3?rlkey=5f2p3pxqfqvfh822dd6p8r3ff&st=6k2f97rg&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGAYXUAEMDEN-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/zbhx01sohlo7dbbjbzupl/NGAYXUAEMDEN-LYRIC.lrc?rlkey=k3vxx1pgpl730seyzvg5y391l&st=4igqjbao&dl=0",
    },
    {
        id: "KTLGK",
        name: "Không Thể Làm Gì Khác (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/KHONGTHELAMGIKHAC-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/nlsxte1kcphd98x1eidtv/KHONGTHELAMGIKHAC-XUANKEN.mp3?rlkey=c2krd5ouk0xa03l8sgcz0c9rh&st=z5k3qwfi&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/KHONGTHELAMGIKHAC-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/i8ercky4d5c8lfhk98lmh/KHONGTHELAMGIKHAC-LYRIC.lrc?rlkey=nblykxb6h5dikquawkyibtmka&st=aamrdiyz&dl=0",
    },
    {
        id: "CCTH",
        name: "Cam Chịu Tủi Hờn (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/CAMCHIUTUIHON-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/3j9nlmfiefgg8h263iqtj/CAMCHIUTUIHON-XUANKEN.mp3?rlkey=q7tkezea82easyvjw5s141k23&st=gn01xe77&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/CAMCHIUTUIHON-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/ckobbuz621cw22md536jw/CAMCHIUTUIHON-LYRIC.lrc?rlkey=25114tx5pqf5gculhahdv2zp7&st=c6dbfkxy&dl=0",
    },
    {
        id: "VQ",
        name: "Vu Quy (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/VUQUY-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/pstgblsd7d5zp2dgoydtb/VUQUY-XUANKEN.mp3?rlkey=4hif7sw0evd3xxksyj0n5kblj&st=ifasqmkv&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/VUQUY-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/bsrhthpkn1kf211kqcd2n/VUQUY-LYRIC.lrc?rlkey=6ui3s7zpp8agvhortgjhbet7w&st=s7lc8o19&dl=0",
    },
    {
        id: "ELCBT2",
        name: "Em Là Cả Bầu Trời 2 (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/EMLACABAUTROI2-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/yy3puxhph11602isvsugw/EMLACABAUTROI2-XUANKEN.mp3?rlkey=3yf2w8vjrgx4btmakggfppes1&st=e70piblq&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/EMLACABAUTROI2-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "TKCERMK",
        name: "Từ Khi Có Em (Remake)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TUKHICOEMREMAKE-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/ld2mn9y4xrs9ufu3ai1b7/TUKHICOEMREMAKE-XUANKEN.mp3?rlkey=alogpyc2v1v5hxlfyoneh2kec&st=s5e0fvxk&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TUKHICOEMREMAKE-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "NMRNU",
        name: "Nước Mắt Rơi (Version Nữ) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NUOCMATROINU-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/o4jrmqoz62h9l0m8nlh76/NUOCMATROINU-XUANKEN.mp3?rlkey=c3as9jr8nwo4ts3mukun9y9eh&st=8fb1gnnu&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NUOCMATROINU-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "NMRNA",
        name: "Nước Mắt Rơi (Version Nam) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NUOCMATROINAM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/cj69tou602cft2hoew0lq/NUOCMATROINAM-XUANKEN.mp3?rlkey=9dbaw2pqw7f9my1vlgiw6fjga&st=ee8xkayk&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NUOCMATROINAM-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "NEDN",
        name: "Ngày Em Đẹp Nhất (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGAYEMDEPNHAT-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/4xsetqxi5vsxjhoim3se6/NGAYEMDEPNHAT-XUANKEN.mp3?rlkey=7zzzc6si03qflrhrlm3r4itge&st=6inq4ja4&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGAYEMDEPNHAT-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "SNCTNU",
        name: "Say Nắng Chiều Tà (Version Nữ) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAYNANGCHIEUTANU-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/ahmci3djtc27esedcc56x/SAYNANGCHIEUTANU-XUANKEN.mp3?rlkey=2m6c8mx8fpn2hmsi8dvwukgyu&st=pwk1ssf1&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAYNANGCHIEUTANU-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "SNCTNA",
        name: "Say Nắng Chiều Tà (Version Nam) (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/SAYNANGCHIEUTANAM-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/92r9j5r796ejd0zcuy891/SAYNANGCHIEUTANAM-XUANKEN.mp3?rlkey=h933d3lxtc76tuz8re46psigh&st=hu0w0vap&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/SAYNANGCHIEUTANAM-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "PBN",
        name: "Phim Ba Người (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/PHIMBANGUOI-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/l5tkq8gagfr6jp6n9lu4t/PHIMBANGUOI-XUANKEN.mp3?rlkey=1tzlmxdm10pajswc0wpsuuivk&st=o8jsi5i1&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/PHIMBANGUOI-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "NDLA",
        name: "Người Đau Là Anh",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NGUOIDAULAANH-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/myc2kewaoniwpvy4qxtje/NGUOIDAULAANH-XUANKEN.mp3?rlkey=jfrbtpnbe0im3fgbrn230kvmz&st=iqffzl3q&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NGUOIDAULAANH-LYRIC.lrc",
        lrc2: "https://dl.dropboxusercontent.com/scl/fi/kcebtaakas6ldx7utxq8i/NGUOIDAULAANH-LYRIC.lrc?rlkey=6qhbnb1lx6l0gr4gkprutgtap&st=zum542bb&dl=0",
    },
    {
        id: "HDCD",
        name: "Hòn Đá Cô Đơn (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/HONDACODON-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/ki5vzo4c300945oc7val6/HONDACODON-XUANKEN.mp3?rlkey=r8eacc8krzpxdnv29uvntjwfx&st=2qfg1p29&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/HONDACODON-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "NDCM",
        name: "Nắng Dưới Chân Mây (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/NANGDUOICHANMAY-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/eizjfie5urez59orb9oit/NANGDUOICHANMAY-XUANKEN.mp3?rlkey=2h8to77of599ay911saobr4xo&st=phvpuo3y&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/NANGDUOICHANMAY-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "TTLM",
        name: "Tự Thương Lấy Mình (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/TUTHUONGLAYMINH-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/gtmkbl0oqy0c5zly0e9hy/TUTHUONGLAYMINH-XUANKEN.mp3?rlkey=it9ckweytvd98q0x1xiyuis98&st=dx67terb&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/TUTHUONGLAYMINH-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "XLENATT",
        name: "Xin Lỗi Em Người Anh Từng Thương (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/XINLOIEMNGUOIANHTUNGTHUONG-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/6k3tw1she2y9eup48xov3/XINLOIEMNGUOIANHTUNGTHUONG-XUANKEN.mp3?rlkey=7v5r57t0v3s6a0ilwa7e7hgs3&st=ena6vp9h&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/XINLOIEMNGUOIANHTUNGTHUONG-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "MHTT",
        name: "Mất Hết Tất Cả (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/MATHETTATCA-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/2uc8fi6ldbh7kibk4z819/MATHETTATCA-XUANKEN.mp3?rlkey=646grevuncu42njy4efwamasa&st=an07m7lt&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/MATHETTATCA-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "GLT",
        name: "Giọt Lệ Tình (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/GIOTLETINH-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/yuq1pmc03kc6xrtx1opor/GIOTLETINH-XUANKEN.mp3?rlkey=k8eom8wkl35trpw8dn1jb20m1&st=sgvmk87z&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/GIOTLETINH-LYRIC.lrc",
        lrc2: "",
    },
    {
        id: "PKBB",
        name: "Phận Kẻ Bọt Bèo (Cover)",
        audio1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/musicofficial/PHANKEBOTBEO-XUANKEN.mp3",
        audio2: "https://dl.dropboxusercontent.com/scl/fi/f2hzo5e41jp0ke75ad9j2/PHANKEBOTBEO-XUANKEN.mp3?rlkey=d3nhfr9w1z7hcbrmo4k0tngbu&st=84r0yp2f&dl=0",
        lrc1: "https://raw.githubusercontent.com/nokiapro/xuankenofficial/main/lyric/PHANKEBOTBEO-LYRIC.lrc",
        lrc2: "",
    },
];
